version: '3.3'
services:
    home-assistant:
        image: homeassistant/home-assistant
        container_name: home_assistant
        restart: always
        network_mode: host
        volumes:
            - ./config:/config
        environment:
            TZ: Europe/Berlin