version: '3.3'
services:
    homebridge:
        image: oznu/homebridge
        container_name: homebridge
        restart: always
        network_mode: host
        volumes:
            - ./data:/homebridge
        environment:
            DSM_HOSTNAME: MariusHosting
            PACKAGES: ffmpeg