version: '3.3'
services:
    openhab:
        image: 'openhab/openhab:latest'
        container_name: openhab
        restart: always
        volumes:
            - ./conf:/openhab/conf
            - ./addons:/openhab/addons
            - ./userdata:/openhab/userdata
        ports:
            - '7100:8080'