version: '3'
services:
  whatsupdocker:
    image: fmartinou/whats-up-docker
    container_name: 'wud'
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock