version: "3.9"
services:
  db:
    image: mariadb:jammy
    container_name: Moodle-DB
    hostname: moodle-db
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: out=$$(mysqladmin ping -h localhost -P 3306 -u root --password=rootpass 2>&1); echo $$out | grep 'mysqld is alive' || { echo $$out; exit 1; }
    environment:
      TZ: Europe/Bucharest
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodleuser
      MYSQL_PASSWORD: moodlepass
    volumes:
      - ./db:/var/lib/mysql:rw
    restart: always

  moodle:
    image: bitnami/moodle:latest
    container_name: Moodle
    hostname: moodle
    security_opt:
      - no-new-privileges:true
    ports:
      - 9490:8080
    environment:
      MOODLE_DATABASE_HOST: moodle-db
      MOODLE_DATABASE_PORT_NUMBER: 3306
      MOODLE_DATABASE_NAME: moodle
      MOODLE_DATABASE_USER: moodleuser
      MOODLE_DATABASE_PASSWORD: moodlepass
      PHP_MEMORY_LIMIT: 512M
      MOODLE_USERNAME: marius
      MOODLE_PASSWORD: mariushosting
      MOODLE_SITE_NAME: Learn With Marius
    volumes:
      - ./data1:/bitnami/moodle
      - ./data2:/bitnami/moodledata
    restart: always
    depends_on:
      db:
        condition: service_started
