version: '3.9'
services:
  typemill:
    container_name: Typemill
    image: oled01/typemill
    healthcheck:
     test: curl -f http://localhost:80/ || exit 1
    ports:
      - 8790:80
    volumes:
      - ./settings:/var/www/html/settings
      - ./cache:/var/www/html/cache
      - ./content:/var/www/html/content
      - ./media:/var/www/html/media
      - ./themes:/var/www/html/themes
      - ./plugins:/var/www/html/plugins
    environment:
      TYPEMILL_UID: 1026
      TYPEMILL_GID: 100
    restart: on-failure:5