version: '3.3'
services:
    linuxserver:
        image: ghcr.io/linuxserver/nzbget
        container_name: nzbget
        restart: always
        volumes:
            - ./config:/config
            - ./downloads:/downloads
        ports:
            - '6789:6789'
        environment:
            PUID: 1026
            PGID: 100
            TZ: Europe/Berlin
