version: '3.3'
services:
    linuxserver:
        image: ghcr.io/linuxserver/radarr
        container_name: radarr
        restart: always
        volumes:
            - ./config:/config
        ports:
            - '7878:7878'
        environment:
            - PUID=1026
            - PGID=100
            - TZ=Europe/Berlin