version: '3.3'
services:
    linuxserver:
        image: ghcr.io/linuxserver/sonarr
        container_name: sonarr
        restart: always
        volumes:
            - ./config:/config
        ports:
            - '8989:8989'
        environment:
            PUID: 1026
            PGID: 100
            TZ: Europe/Berlin