version: "3.9"
services:
  remotely:
    image: immybot/remotely:latest
    container_name: remotely
    hostname: remotely
    mem_limit: 1g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    ports:
      - 5043:5000
    volumes:
      - ./remotely:/remotely-data
    restart: on-failure:5
