version: "3.3"
services:
    it-tools:
        image: corentinth/it-tools:latest
        container_name: it-tools
        restart: unless-stopped
        ports:
            - '80:80'
        lables:
          - "traefik.enable=true"
          - "traefik.http.routers.nginx.rule=Host(`docker.der-ithieler.cloud`)"
        networks:
          - traefik

networks:
  traefik:
    external: true
    name: traefik
