version: '3.3'
services:
    linuxserver:
        image: 'lscr.io/linuxserver/unifi-controller:latest'
        container_name: unifi-controller
        restart: unless-stopped
        ports:
            - '8443:8443'
            - '3478:3478/udp'
            - '10001:10001/udp'
            - '8080:8080'
            - '1900:1900/udp'
            - '8843:8843'
            - '8880:8880'
            - '6789:6789'
            - '5514:5514/udp'
        volumes:
            - ./data:/config
        environment:
            PUID: 1026
            PGID: 100
            TZ: Europe/Berlin
            MEM_LIMIT: 1024
            MEM_STARTUP: 1024
