version: "3.3"
services:
    watchyourlan:
        image: aceberg/watchyourlan
        container_name: WatchYourLAN
        restart: always
        network_mode: host
        volumes:
            - './data:/data'
        environment:
            TZ: Europe/Berlin
            GUIIP: 192.168.1.18
            GUIPORT: 8840
            IFACE: bond0
            THEME: darkly
