version: "3.9"
services:
  redis:
    image: redis
    container_name: Bar-Assistant-REDIS
    hostname: barassistant-redis
    mem_limit: 256m
    mem_reservation: 50m
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    read_only: true
    user: 1026:100
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping || exit 1"]
    volumes:
      - ./redis:/data:rw
    environment:
      TZ: Europe/Berlin
      ALLOW_EMPTY_PASSWORD: yes
    restart: on-failure:5

  meilisearch:
    image: getmeili/meilisearch:v1.0.2
    container_name: Bar-Assistant-SEARCH
    hostname: barassistant-search
    mem_limit: 512m
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:7700
    volumes:
      - ./meilisearch:/meili_data:rw
    environment:
      MEILI_MASTER_KEY: LxgEN9GPU2xhjtJseX2d5j7DP49Uv4Bg
      MEILI_ENV: production
    restart: on-failure:5

  bar-assistant:
    image: barassistant/server:latest
    container_name: Bar-Assistant
    hostname: barassistant
    mem_limit: 512m
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true

    volumes:
      - ./bar-data:/var/www/cocktails/storage/bar-assistant:rw
    environment:
      APP_URL: https://bar.yourname.synology.me/bar
      LOG_CHANNEL: stderr
      MEILISEARCH_KEY: LxgEN9GPU2xhjtJseX2d5j7DP49Uv4Bg
      MEILISEARCH_HOST: http://barassistant-search:7700
      REDIS_HOST: barassistant-redis
      CACHE_DRIVER: redis
      SESSION_DRIVER: redis
      ALLOW_REGISTRATION: true
    restart: on-failure:5
    depends_on:
      meilisearch:
        condition: service_healthy
      redis:
        condition: service_healthy

  salt-rim:
    image: barassistant/salt-rim:latest
    container_name: Bar-Assistant-SALT-RIM
    hostname: barassistant-salt-rim
    mem_limit: 512m
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: curl -f http://localhost:8080/ || exit 1
    environment:
      API_URL: https://bar.yourname.synology.me/bar
      MEILISEARCH_URL: https://bar.yourname.synology.me/search
    restart: on-failure:5
    depends_on:
      bar-assistant:
        condition: service_started

  webserver:
    image: nginx:alpine
    container_name: Bar-Assistant-WEB
    hostname: barassistant-web
    mem_limit: 512m
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:3000
    ports:
      - 4200:3000
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    restart: on-failure:5
    depends_on:
      salt-rim:
        condition: service_healthy
